obstacles:
  - type: rectangle
    xlims: [2.3, 3.4]
    ylims: [7, 9.8]

  - type: rectangle
    xlims: [7.3, 8.5]
    ylims: [7.6, 10]

  - type: rectangle
    xlims: [1.3, 3]
    ylims: [2.8, 3.8]

  - type: rectangle
    xlims: [5, 7.1]
    ylims: [0.9, 3.7]

robot:
  type: RobotArm2D
  parameters:
    base_position: [5.0, 5.0]
    link_lengths: [2.1, 2.1]